# Generated by Django 4.2.4 on 2023-08-29 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, choices=[('development', 'Development'), ('design', 'Design'), ('communication', 'Communication'), ('relex-logistics', 'Relex and logistics'), ('multimedia', 'Multimedia')], max_length=100, null=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('meet', 'Meeting'), ('task', 'Task'), ('event-participation', 'event participation'), ('event-organization', 'event organization')], max_length=100)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=10)),
                ('department', models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('communication', 'Communication'), ('relex-logistics', 'Relex and logistics'), ('multimedia', 'Multimedia')], max_length=100)),
                ('members', models.ManyToManyField(related_name='activities', to='members.member')),
            ],
        ),
    ]
