# Generated by Django 4.2.4 on 2023-11-18 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('department', models.ManyToManyField(blank=True, related_name='members', to='members.department')),
                ('team', models.ManyToManyField(blank=True, related_name='members', to='members.team')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('meet', 'Meeting'), ('task', 'Task'), ('part', 'event participation'), ('organ', 'event organization')], max_length=100)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=10)),
                ('department', models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('communication', 'Communication'), ('relex-logistics', 'Relex and logistics'), ('multimedia', 'Multimedia')], max_length=100)),
                ('importance', models.CharField(choices=[('training', 'Training'), ('important', 'Important'), ('obligatory', 'Obligatory')], default='training', max_length=100)),
                ('time', models.CharField(choices=[('quick', 'Quick'), ('takes-time', 'Takes time'), ('ongoing', 'Ongoing')], default='quick', max_length=100)),
                ('members', models.ManyToManyField(blank=True, related_name='activities', to='members.member')),
            ],
        ),
    ]
