# Generated by Django 4.2.4 on 2023-11-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
