# Generated by Django 4.2.4 on 2023-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_activities_importance_activities_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='time',
            field=models.CharField(choices=[('quick', 'Quick'), ('takes-time', 'Takes time'), ('ongoing', 'Ongoing')], default='quick', max_length=100),
        ),
    ]
