# Generated by Django 4.2.4 on 2023-08-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_activities_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='activities', to='members.member'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='type',
            field=models.CharField(choices=[('meet', 'Meeting'), ('task', 'Task'), ('part', 'event participation'), ('organ', 'event organization')], max_length=100),
        ),
    ]
