# Generated by Django 4.2.5 on 2023-10-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_activities_members_alter_activities_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='importance',
            field=models.CharField(choices=[('training', 'Training'), ('important', 'Important'), ('obligatory', 'Obligatory')], default='training', max_length=100),
        ),
    ]
